version: '3.7'

networks:
  nginx-proxy-manager:
    external: true

services:
  snippetbox:
    image: pawelmalak/snippet-box
    container_name: ${COMPOSE_PROJECT_NAME}_snippetbox
    ports:
      - '${SNIPPETBOX_HTTP_PORT:-9997}:5000'
    volumes:
      - './data:/app/data'
    networks:
      - nginx-proxy-manager
